# Generated by Django 5.1.1 on 2024-09-26 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculo', '0003_remove_vehiculo_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='consumo_promedio',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='potencia',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='tanque_combustible',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='traccion',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='transmision',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
