# Generated by Django 5.1.1 on 2024-09-26 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculo', '0005_vehiculo_cilindrada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='potencia',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
