# Generated by Django 5.1.1 on 2024-09-26 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculo', '0006_alter_vehiculo_potencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='tanque_combustible',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
