# Generated by Django 5.1.1 on 2024-09-26 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculo', '0007_alter_vehiculo_tanque_combustible'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehiculo',
            old_name='consumo_promedio',
            new_name='motor',
        ),
        migrations.RemoveField(
            model_name='vehiculo',
            name='cilindrada',
        ),
    ]
