# Generated by Django 5.1.1 on 2024-09-27 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculo', '0008_rename_consumo_promedio_vehiculo_motor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='motor',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
