# Generated by Django 5.1.1 on 2024-09-27 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculo', '0009_alter_vehiculo_motor'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
