# Generated by Django 5.1.1 on 2024-09-28 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculo', '0010_vehiculo_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='descripcion',
            field=models.TextField(blank=True, default='Sin información', null=True),
        ),
    ]
