# Generated by Django 5.1.1 on 2024-10-01 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculo', '0014_alter_vehiculo_kilometraje'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='kilometraje',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15, null=True),
        ),
    ]
