# Generated by Django 5.1.1 on 2024-10-01 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculo', '0016_alter_vehiculo_kilometraje'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='kilometraje',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
