# Generated by Django 5.1.1 on 2024-10-25 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculo', '0020_alter_modeloformulariobusqueda_año_fin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='descripcion',
            field=models.CharField(blank=True, default='Sin información', max_length=500, null=True),
        ),
    ]
