# Generated by Django 5.1.1 on 2025-04-25 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculo', '0022_alter_vehiculo_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modeloformulariobusqueda',
            name='año_fin',
            field=models.PositiveIntegerField(blank=True, choices=[(2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023), (2024, 2024), (2025, 2025)], default='None', null=True),
        ),
        migrations.AlterField(
            model_name='modeloformulariobusqueda',
            name='año_inicio',
            field=models.PositiveIntegerField(blank=True, choices=[(2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023), (2024, 2024), (2025, 2025)], default='None', null=True),
        ),
    ]
