# Generated by Django 5.1.1 on 2025-04-29 18:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculo', '0023_alter_modeloformulariobusqueda_año_fin_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormularioBusqueda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=100)),
                ('numero_celular', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Formato de número incorrecto. Intente nuevamente.', regex='^\\+?1?\\d{9,15}$')])),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('año_inicio', models.PositiveIntegerField(blank=True, choices=[(2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023), (2024, 2024), (2025, 2025)], default=None, null=True)),
                ('año_fin', models.PositiveIntegerField(blank=True, choices=[(2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023), (2024, 2024), (2025, 2025)], default=None, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='ModeloFormularioBusqueda',
        ),
    ]
